/**
 * California AI Visual Inspection — opportunity dataset.
 *
 * California manufacturers with physical production whose quality-inspection
 * profile fits deep-learning / edge AI visual inspection. Compiled from public
 * information; locations reflect a principal California site, not necessarily HQ.
 *
 * Each record carries:
 *   fit  — "Very High" | "High" (suitability for AI visual inspection)
 *   use  — what they make / the inspection context
 *   why  — reasoning behind the fit rating
 *   win  — how to win the account (the wedge / sales play)
 *
 * Coordinates are looked up from CITY_COORDS by city (approximate city centroids).
 */

window.CITY_COORDS = {
  "Redondo Beach": [33.849, -118.388], "Palmdale": [34.579, -118.116],
  "El Segundo": [33.919, -118.416], "Hawthorne": [33.916, -118.352],
  "Canoga Park": [34.201, -118.598], "Thousand Oaks": [34.171, -118.838],
  "Costa Mesa": [33.641, -117.919], "Long Beach": [33.770, -118.194],
  "Torrance": [33.836, -118.341], "Los Angeles": [34.052, -118.244],
  "Simi Valley": [34.269, -118.781], "Mojave": [35.052, -118.174],
  "Chatsworth": [34.257, -118.601], "Cerritos": [33.858, -118.065],
  "Vernon": [34.003, -118.230], "Westlake Village": [34.146, -118.806],
  "Garden Grove": [33.774, -117.937], "Santa Ana": [33.746, -117.868],
  "Irvine": [33.684, -117.793], "Fountain Valley": [33.709, -117.954],
  "Rancho Santa Margarita": [33.641, -117.603], "Carlsbad": [33.158, -117.351],
  "San Diego": [32.716, -117.161], "Ontario": [34.063, -117.651],
  "Rancho Cucamonga": [34.106, -117.593], "Bakersfield": [35.373, -119.019],
  "Lost Hills": [35.616, -119.692], "Kingsburg": [36.514, -119.554],
  "Livingston": [37.387, -120.723], "Salinas": [36.677, -121.655],
  "Watsonville": [36.910, -121.757], "Marina": [36.684, -121.802],
  "Sacramento": [38.582, -121.494], "Folsom": [38.678, -121.176],
  "Santa Rosa": [38.440, -122.714], "San Francisco": [37.775, -122.419],
  "South San Francisco": [37.655, -122.408], "Santa Clara": [37.354, -121.955],
  "San Jose": [37.339, -121.895], "Sunnyvale": [37.369, -122.036],
  "Milpitas": [37.428, -121.907], "Fremont": [37.548, -121.989],
  "Newark": [37.530, -122.040], "San Mateo": [37.563, -122.326],
  "Foster City": [37.558, -122.271], "Alameda": [37.765, -122.242],
  "Redwood City": [37.485, -122.236], "Mountain View": [37.386, -122.084],
  "Palo Alto": [37.442, -122.143], "Campbell": [37.287, -121.950]
};

window.COMPANIES = [
  // ---- Aerospace, Defense & Space ----
  { name: "Northrop Grumman", type: "Enterprise", vertical: "Aerospace, Defense & Space", region: "Greater LA / South Bay", city: "Redondo Beach", fit: "Very High", use: "Space & defense structures and electronics.", why: "Zero-defect parts with full traceability; manual inspection is slow and costly.", win: "Lead with traceability + escape cost; eval on a high-rework subassembly, align to AS9100." },
  { name: "Lockheed Martin (Skunk Works)", type: "Enterprise", vertical: "Aerospace, Defense & Space", region: "Antelope Valley", city: "Palmdale", fit: "Very High", use: "Advanced and classified airframes.", why: "Ultra-high-value, low-volume parts where a single escape is catastrophic.", win: "Sell risk reduction over throughput; start in a non-classified cell to prove the workflow." },
  { name: "Boeing", type: "Enterprise", vertical: "Aerospace, Defense & Space", region: "Greater LA / South Bay", city: "El Segundo", fit: "Very High", use: "Aerostructures and satellites.", why: "Large parts with variable surface defects rule-based vision misses.", win: "Bench against the incumbent AOI on their worst defect class; expand station by station." },
  { name: "RTX (Raytheon)", type: "Enterprise", vertical: "Aerospace, Defense & Space", region: "Greater LA / South Bay", city: "El Segundo", fit: "High", use: "Defense electronics and subsystems.", why: "High-mix electronics QC, but much inspection is already automated.", win: "Target solder/conformal-coat defects their current AOI flags as false positives." },
  { name: "SpaceX", type: "Startup/Scale-up", vertical: "Aerospace, Defense & Space", region: "Greater LA / South Bay", city: "Hawthorne", fit: "Very High", use: "Rockets and Starlink at high rate.", why: "Highest production rate in aerospace; scrap on engines/avionics is expensive.", win: "Sell deploy speed to keep pace with the rate ramp; embed on a Starlink line." },
  { name: "Aerojet Rocketdyne", type: "Enterprise", vertical: "Aerospace, Defense & Space", region: "Greater LA / South Bay", city: "Canoga Park", fit: "High", use: "Rocket propulsion systems.", why: "Critical propulsion parts, lower volume.", win: "Lead with weld/braze inspection and documentation for critical joints." },
  { name: "Teledyne Technologies", type: "Enterprise", vertical: "Aerospace, Defense & Space", region: "Greater LA / South Bay", city: "Thousand Oaks", fit: "High", use: "Imaging, sensors, instruments.", why: "Diverse precision electronics and optics across business units.", win: "Find one high-volume sensor line; prove yield lift, then expand across units." },
  { name: "Anduril Industries", type: "Startup/Scale-up", vertical: "Aerospace, Defense & Space", region: "Orange County", city: "Costa Mesa", fit: "Very High", use: "Autonomous defense hardware.", why: "Scaling production fast with a software-first culture receptive to AI.", win: "Speak software-defined manufacturing; embed during a new product line bring-up." },
  { name: "Relativity Space", type: "Startup/Scale-up", vertical: "Aerospace, Defense & Space", region: "Greater LA / South Bay", city: "Long Beach", fit: "Very High", use: "3D-printed launch vehicles.", why: "Novel additive processes need inspection rule-based vision can't model.", win: "Position as the inspection layer for additive variability; co-develop acceptance criteria." },
  { name: "Rocket Lab", type: "Startup/Scale-up", vertical: "Aerospace, Defense & Space", region: "Greater LA / South Bay", city: "Long Beach", fit: "Very High", use: "Launch vehicles and space systems.", why: "Growing production of high-value flight hardware.", win: "Win a composites or avionics station; expand with each new product." },
  { name: "Vast", type: "Startup/Scale-up", vertical: "Aerospace, Defense & Space", region: "Greater LA / South Bay", city: "Long Beach", fit: "High", use: "Commercial space-station hardware.", why: "Ramping hardware production now.", win: "Get in during line setup before processes ossify." },
  { name: "Varda Space Industries", type: "Startup/Scale-up", vertical: "Aerospace, Defense & Space", region: "Greater LA / South Bay", city: "El Segundo", fit: "High", use: "In-space manufacturing capsules.", why: "Precision reentry hardware, early volume.", win: "Small-footprint eval on capsule structure; grow with cadence." },
  { name: "Impulse Space", type: "Startup/Scale-up", vertical: "Aerospace, Defense & Space", region: "Greater LA / South Bay", city: "Redondo Beach", fit: "High", use: "Orbital transfer vehicles.", why: "Propulsion hardware, scaling.", win: "Target propulsion-component inspection; expand as flight rate grows." },
  { name: "Hadrian", type: "Startup/Scale-up", vertical: "Aerospace, Defense & Space", region: "Greater LA / South Bay", city: "Torrance", fit: "Very High", use: "Automated precision machining.", why: "Inspection-native automated factory; vision is core to their model.", win: "Partner as their in-line QC layer; one win scales to every new factory they stand up." },
  { name: "Apex Space", type: "Startup/Scale-up", vertical: "Aerospace, Defense & Space", region: "Greater LA / South Bay", city: "Los Angeles", fit: "Very High", use: "Productized satellite buses.", why: "Volume satellite manufacturing — repeatable, high-value units.", win: "Embed on the bus line; one win scales across every bus produced." },
  { name: "K2 Space", type: "Startup/Scale-up", vertical: "Aerospace, Defense & Space", region: "Greater LA / South Bay", city: "Torrance", fit: "High", use: "Large high-power satellites.", why: "Building satellite production capacity now.", win: "Get in early on structure/harness inspection during scale-up." },
  { name: "ABL Space Systems", type: "Startup/Scale-up", vertical: "Aerospace, Defense & Space", region: "Greater LA / South Bay", city: "El Segundo", fit: "High", use: "Launch systems.", why: "Ramping launch hardware production.", win: "Target engine/structure inspection on the next build cycle." },
  { name: "AeroVironment", type: "Enterprise", vertical: "Aerospace, Defense & Space", region: "Greater LA / South Bay", city: "Simi Valley", fit: "Very High", use: "Tactical drones (public).", why: "Higher-volume drone production mixing electronics and composites.", win: "Lead with mixed electronics/composite defect detection; expand by product family." },
  { name: "General Atomics", type: "Enterprise", vertical: "Aerospace, Defense & Space", region: "San Diego", city: "San Diego", fit: "High", use: "MQ drones and defense systems.", why: "Large defense platforms, lower volume.", win: "Target a high-rework subassembly; document for defense QA." },
  { name: "Scaled Composites", type: "Enterprise", vertical: "Aerospace, Defense & Space", region: "Antelope Valley", city: "Mojave", fit: "High", use: "Experimental composite aircraft.", why: "Composite layup defects, low volume.", win: "Target composite surface/ply inspection." },
  { name: "Astranis", type: "Startup/Scale-up", vertical: "Aerospace, Defense & Space", region: "Bay Area", city: "San Francisco", fit: "High", use: "Small GEO satellites.", why: "Batch satellite assembly.", win: "Win the assembly inspection station; grow with the constellation." },
  { name: "Planet Labs", type: "Startup/Scale-up", vertical: "Aerospace, Defense & Space", region: "Bay Area", city: "San Francisco", fit: "High", use: "High-volume small satellites.", why: "Assembly-line satellite production.", win: "Pitch repeatability across identical units." },

  // ---- Semiconductor & Electronics ----
  { name: "Intel", type: "Enterprise", vertical: "Semiconductor & Electronics", region: "Sacramento Region", city: "Folsom", fit: "Very High", use: "Chip design, validation, packaging.", why: "Sub-micron defects with massive yield dollars per percentage point.", win: "Target a defect class their AOI misses; quantify yield $ to justify the eval." },
  { name: "Applied Materials", type: "Enterprise", vertical: "Semiconductor & Electronics", region: "Bay Area", city: "Santa Clara", fit: "Very High", use: "Semiconductor fab equipment.", why: "Precision equipment assembly with tight tolerances.", win: "Win a component-inspection cell; expand across tool lines." },
  { name: "Lam Research", type: "Enterprise", vertical: "Semiconductor & Electronics", region: "Bay Area", city: "Fremont", fit: "Very High", use: "Wafer-fab equipment.", why: "Complex precision assemblies, high rework cost.", win: "Target a high-rework module; prove first-pass yield." },
  { name: "KLA", type: "Enterprise", vertical: "Semiconductor & Electronics", region: "Bay Area", city: "Milpitas", fit: "Very High", use: "Metrology and inspection systems.", why: "They build inspection tools — high bar, but a huge internal QC need.", win: "Position as complementary in-line QC on their own assembly lines." },
  { name: "Western Digital", type: "Enterprise", vertical: "Semiconductor & Electronics", region: "Bay Area", city: "San Jose", fit: "Very High", use: "Storage devices.", why: "High-volume micro-assembly with tiny defects.", win: "Target head/media handling defects at volume." },
  { name: "Nvidia", type: "Enterprise", vertical: "Semiconductor & Electronics", region: "Bay Area", city: "Santa Clara", fit: "High", use: "GPUs and systems (largely fabless).", why: "Mostly fabless; QC happens at board/system level.", win: "Target DGX/board assembly inspection, not wafers." },
  { name: "Broadcom", type: "Enterprise", vertical: "Semiconductor & Electronics", region: "Bay Area", city: "Palo Alto", fit: "High", use: "Semiconductors (largely outsourced).", why: "Production mostly outsourced.", win: "Target final module/optical assembly done in-house." },
  { name: "Qualcomm", type: "Enterprise", vertical: "Semiconductor & Electronics", region: "San Diego", city: "San Diego", fit: "High", use: "Mobile and RF chipsets.", why: "Mostly fabless; some module/test in-house.", win: "Target RF module assembly and test escapes." },
  { name: "Skyworks Solutions", type: "Enterprise", vertical: "Semiconductor & Electronics", region: "Orange County", city: "Irvine", fit: "Very High", use: "RF semiconductors and modules.", why: "In-house high-volume RF module production.", win: "Target wire-bond/module defects; expand by product line." },
  { name: "Kingston Technology", type: "Enterprise", vertical: "Semiconductor & Electronics", region: "Orange County", city: "Fountain Valley", fit: "Very High", use: "Memory modules at volume.", why: "Very high-volume assembly with repetitive defects.", win: "Prove on one DIMM line; scale by SKU and shift." },
  { name: "Super Micro Computer", type: "Enterprise", vertical: "Semiconductor & Electronics", region: "Bay Area", city: "San Jose", fit: "Very High", use: "Servers and systems assembly.", why: "High-mix, high-volume board and chassis assembly.", win: "Target solder/connector defects on the highest-runner board." },
  { name: "Sanmina", type: "Enterprise", vertical: "Semiconductor & Electronics", region: "Bay Area", city: "San Jose", fit: "Very High", use: "Contract electronics manufacturing.", why: "EMS with diverse high-volume PCBA lines.", win: "Land one customer program; expand across their factory." },
  { name: "Coherent", type: "Enterprise", vertical: "Semiconductor & Electronics", region: "Bay Area", city: "Santa Clara", fit: "High", use: "Lasers and photonics.", why: "Precision optical assembly.", win: "Target optical surface/alignment inspection." },
  { name: "Lumentum", type: "Enterprise", vertical: "Semiconductor & Electronics", region: "Bay Area", city: "San Jose", fit: "High", use: "Optical components.", why: "Micro-optics with tight tolerances.", win: "Target a high-yield-loss optical step." },
  { name: "Seagate", type: "Enterprise", vertical: "Semiconductor & Electronics", region: "Bay Area", city: "Fremont", fit: "High", use: "Storage R&D and pilot production.", why: "Pilot/precision production in California.", win: "Target head-assembly defect classes." },

  // ---- Medical Devices ----
  { name: "Edwards Lifesciences", type: "Enterprise", vertical: "Medical Devices", region: "Orange County", city: "Irvine", fit: "Very High", use: "Heart valves at high volume.", why: "Life-critical, FDA-regulated, and manual-inspection heavy.", win: "Lead with recall avoidance + validation; align acceptance criteria to their QMS." },
  { name: "Boston Scientific", type: "Enterprise", vertical: "Medical Devices", region: "Greater LA / South Bay", city: "Torrance", fit: "Very High", use: "Implantable devices.", why: "Regulated, defect-critical, high volume.", win: "Target a manual visual-inspection station with high labor cost." },
  { name: "Masimo", type: "Enterprise", vertical: "Medical Devices", region: "Orange County", city: "Irvine", fit: "Very High", use: "Patient-monitoring sensors.", why: "High-volume electronics and sensors.", win: "Target sensor assembly defects; expand into electronics." },
  { name: "Applied Medical", type: "Enterprise", vertical: "Medical Devices", region: "Orange County", city: "Rancho Santa Margarita", fit: "Very High", use: "Surgical devices, vertically integrated.", why: "In-house high-volume production end to end.", win: "One station win scales across a vertically integrated plant." },
  { name: "Intuitive Surgical", type: "Enterprise", vertical: "Medical Devices", region: "Bay Area", city: "Sunnyvale", fit: "Very High", use: "da Vinci surgical robots and instruments.", why: "Precision robotic instruments, regulated, growing volume.", win: "Target single-use instrument inspection at volume; align to FDA QMS." },
  { name: "Dexcom", type: "Enterprise", vertical: "Medical Devices", region: "San Diego", city: "San Diego", fit: "Very High", use: "Continuous glucose monitors.", why: "Massive-volume disposable sensors, defect-sensitive.", win: "Prove on the sensor line; throughput + scrap story scales fast." },
  { name: "Illumina", type: "Enterprise", vertical: "Medical Devices", region: "San Diego", city: "San Diego", fit: "High", use: "DNA sequencers and consumables.", why: "Precision instruments plus high-volume consumables.", win: "Target flow-cell/consumable inspection at volume." },
  { name: "ResMed", type: "Enterprise", vertical: "Medical Devices", region: "San Diego", city: "San Diego", fit: "High", use: "Respiratory devices.", why: "High-volume device assembly.", win: "Target mask/device assembly defects." },
  { name: "Penumbra", type: "Enterprise", vertical: "Medical Devices", region: "Bay Area", city: "Alameda", fit: "High", use: "Neurovascular devices.", why: "Precision catheters and devices, regulated.", win: "Target catheter inspection with a validation-led pitch." },
  { name: "Tandem Diabetes Care", type: "Startup/Scale-up", vertical: "Medical Devices", region: "San Diego", city: "San Diego", fit: "High", use: "Insulin pumps.", why: "Device assembly with growing volume.", win: "Target pump assembly defects with regulated documentation." },

  // ---- EV, Battery & Energy ----
  { name: "Tesla", type: "Enterprise", vertical: "EV, Battery & Energy", region: "Bay Area", city: "Fremont", fit: "Very High", use: "EVs and batteries at scale.", why: "Highest-rate auto plant in CA; paint, weld, and assembly defects abound.", win: "Target a high-scrap body/paint station; the expansion footprint is enormous." },
  { name: "Lucid Motors", type: "Startup/Scale-up", vertical: "EV, Battery & Energy", region: "Bay Area", city: "Newark", fit: "High", use: "Luxury EVs (main plant in AZ).", why: "CA hosts powertrain/engineering; manufacturing is mostly Arizona.", win: "Win CA powertrain inspection, then follow to the AZ plant." },
  { name: "Rivian", type: "Startup/Scale-up", vertical: "EV, Battery & Energy", region: "Orange County", city: "Irvine", fit: "High", use: "EV design and engineering (mfg in IL).", why: "California is design/engineering with limited production.", win: "Land prototyping/validation, then expand to the plants." },
  { name: "Karma Automotive", type: "Startup/Scale-up", vertical: "EV, Battery & Energy", region: "Orange County", city: "Irvine", fit: "High", use: "Luxury EV assembly.", why: "Low-volume assembly in California.", win: "Target paint and fit-and-finish inspection." },
  { name: "Harbinger Motors", type: "Startup/Scale-up", vertical: "EV, Battery & Energy", region: "Orange County", city: "Garden Grove", fit: "High", use: "Medium-duty EV trucks.", why: "Scaling EV truck production.", win: "Embed during line bring-up on chassis and battery assembly." },
  { name: "Aptera Motors", type: "Startup/Scale-up", vertical: "EV, Battery & Energy", region: "San Diego", city: "Carlsbad", fit: "High", use: "Solar EV.", why: "Early composite EV production.", win: "Target composite body inspection at launch." },
  { name: "QuantumScape", type: "Startup/Scale-up", vertical: "EV, Battery & Energy", region: "Bay Area", city: "San Jose", fit: "Very High", use: "Solid-state battery cells.", why: "Defect-sensitive cells; the ramp is yield-driven.", win: "Sell yield lift on separator/cell defects during scale-up." },
  { name: "Enovix", type: "Startup/Scale-up", vertical: "EV, Battery & Energy", region: "Bay Area", city: "Fremont", fit: "Very High", use: "Silicon batteries.", why: "Novel cell production with a yield-critical ramp.", win: "Position as the yield tool for a new process; co-define defects." },
  { name: "Amprius Technologies", type: "Startup/Scale-up", vertical: "EV, Battery & Energy", region: "Bay Area", city: "Fremont", fit: "High", use: "High-energy silicon cells.", why: "Battery production scale-up.", win: "Target electrode/cell defect detection." },
  { name: "Sila Nanotechnologies", type: "Startup/Scale-up", vertical: "EV, Battery & Energy", region: "Bay Area", city: "Alameda", fit: "High", use: "Battery anode materials.", why: "Materials production with some inspection need.", win: "Target coating/material defect inspection." },
  { name: "Natron Energy", type: "Startup/Scale-up", vertical: "EV, Battery & Energy", region: "Bay Area", city: "Santa Clara", fit: "High", use: "Sodium-ion batteries.", why: "New cell chemistry ramping.", win: "Embed early in the production line." },
  { name: "Bloom Energy", type: "Enterprise", vertical: "EV, Battery & Energy", region: "Bay Area", city: "San Jose", fit: "Very High", use: "Solid-oxide fuel cells.", why: "High-value stacks where defects are costly and volume is growing.", win: "Target stack/cell inspection; quantify scrap savings." },

  // ---- Robotics, Drones & eVTOL ----
  { name: "Figure AI", type: "Startup/Scale-up", vertical: "Robotics, Drones & eVTOL", region: "Bay Area", city: "Sunnyvale", fit: "Very High", use: "Humanoid robots.", why: "Precision actuators and assembly, scaling production.", win: "Embed in their first volume line; software-first buyers move fast." },
  { name: "Skydio", type: "Startup/Scale-up", vertical: "Robotics, Drones & eVTOL", region: "Bay Area", city: "San Mateo", fit: "Very High", use: "Autonomous drones at volume.", why: "High-volume assembly mixing electronics and frames.", win: "Target PCBA/frame defects; expand by model." },
  { name: "Zipline", type: "Startup/Scale-up", vertical: "Robotics, Drones & eVTOL", region: "Bay Area", city: "South San Francisco", fit: "High", use: "Delivery drones.", why: "Growing drone production.", win: "Target airframe/electronics inspection." },
  { name: "Archer Aviation", type: "Startup/Scale-up", vertical: "Robotics, Drones & eVTOL", region: "Bay Area", city: "San Jose", fit: "Very High", use: "eVTOL aircraft.", why: "Aerospace-grade defect tolerance, scaling toward volume.", win: "Win a composite/structure station with an aerospace QA story." },
  { name: "Joby Aviation", type: "Startup/Scale-up", vertical: "Robotics, Drones & eVTOL", region: "Central Valley & Coast", city: "Marina", fit: "Very High", use: "eVTOL aircraft.", why: "Composite airframe with certification-driven QC.", win: "Target composite ply/surface inspection; align to FAA requirements." },
  { name: "Wisk Aero", type: "Startup/Scale-up", vertical: "Robotics, Drones & eVTOL", region: "Bay Area", city: "Mountain View", fit: "High", use: "Autonomous eVTOL.", why: "Pre-production / early build.", win: "Get in during prototyping for production design-in." },
  { name: "Overair", type: "Startup/Scale-up", vertical: "Robotics, Drones & eVTOL", region: "Orange County", city: "Santa Ana", fit: "High", use: "eVTOL aircraft.", why: "Early eVTOL development.", win: "Design inspection into the production plan early." },
  { name: "Zoox", type: "Startup/Scale-up", vertical: "Robotics, Drones & eVTOL", region: "Bay Area", city: "Foster City", fit: "High", use: "Autonomous-vehicle hardware.", why: "Robotaxi hardware, limited volume.", win: "Target sensor/assembly inspection." },
  { name: "Saildrone", type: "Startup/Scale-up", vertical: "Robotics, Drones & eVTOL", region: "Bay Area", city: "Alameda", fit: "High", use: "Autonomous maritime vehicles.", why: "Specialized vehicle assembly.", win: "Target hull/electronics inspection." },
  { name: "Bright Machines", type: "Startup/Scale-up", vertical: "Robotics, Drones & eVTOL", region: "Bay Area", city: "San Francisco", fit: "High", use: "Software-defined assembly cells.", why: "They sell automation — a partner, not just a customer.", win: "Integrate vision into their assembly cells as a partner." },
  { name: "Machina Labs", type: "Startup/Scale-up", vertical: "Robotics, Drones & eVTOL", region: "Greater LA / South Bay", city: "Chatsworth", fit: "Very High", use: "Robotic sheet-metal forming.", why: "A novel forming process that needs in-process inspection.", win: "Sell in-process geometry/defect inspection; co-develop with their robotics." },
  { name: "Dexterity", type: "Startup/Scale-up", vertical: "Robotics, Drones & eVTOL", region: "Bay Area", city: "Redwood City", fit: "High", use: "Warehouse and industrial robots.", why: "Robot production plus vision-savvy buyers.", win: "Partner on integrated vision QC." },

  // ---- Food, Beverage & Packaging ----
  { name: "PepsiCo / Frito-Lay", type: "Enterprise", vertical: "Food, Beverage & Packaging", region: "Inland Empire", city: "Rancho Cucamonga", fit: "Very High", use: "Snacks and beverages at high speed.", why: "Extreme throughput; packaging, seal, and label defects.", win: "Prove on one high-speed line with a throughput + labor story; expand by line." },
  { name: "Niagara Bottling", type: "Enterprise", vertical: "Food, Beverage & Packaging", region: "Inland Empire", city: "Ontario", fit: "Very High", use: "Bottled water at huge volume.", why: "Massive throughput; fill, cap, and label defects.", win: "Target fill/cap inspection on the fastest line; then multi-plant rollout." },
  { name: "Smithfield (Farmer John)", type: "Enterprise", vertical: "Food, Beverage & Packaging", region: "Greater LA / South Bay", city: "Vernon", fit: "Very High", use: "Meat processing and packaging.", why: "Contamination plus packaging QC at high volume.", win: "Lead with food-safety + packaging defects; one line, then plant-wide." },
  { name: "The Wonderful Company", type: "Enterprise", vertical: "Food, Beverage & Packaging", region: "Central Valley & Coast", city: "Lost Hills", fit: "Very High", use: "Produce and nuts: sorting and packaging.", why: "Huge volume; grading and foreign-material detection.", win: "Target a grading/sort line; expand across commodities." },
  { name: "Foster Farms", type: "Enterprise", vertical: "Food, Beverage & Packaging", region: "Central Valley & Coast", city: "Livingston", fit: "Very High", use: "Poultry processing.", why: "High-volume processing with defect and packaging QC.", win: "Target a packaging/defect station; multi-line expansion." },
  { name: "Taylor Farms", type: "Enterprise", vertical: "Food, Beverage & Packaging", region: "Central Valley & Coast", city: "Salinas", fit: "Very High", use: "Fresh-cut produce at huge volume.", why: "Foreign-material and quality control at extreme throughput.", win: "Lead with foreign-material detection; expand by line and site." },
  { name: "Driscoll's", type: "Enterprise", vertical: "Food, Beverage & Packaging", region: "Central Valley & Coast", city: "Watsonville", fit: "High", use: "Berry grading and packing.", why: "Quality grading with seasonal volume.", win: "Target berry grading/sort; prove it during peak season." },
  { name: "Blue Diamond Growers", type: "Enterprise", vertical: "Food, Beverage & Packaging", region: "Sacramento Region", city: "Sacramento", fit: "Very High", use: "Almond processing at scale.", why: "High-volume nut sorting; defect and foreign-material detection.", win: "Target sort-line defect/FM detection; expand by line." },
  { name: "Grimmway Farms", type: "Enterprise", vertical: "Food, Beverage & Packaging", region: "Central Valley & Coast", city: "Bakersfield", fit: "Very High", use: "Carrots at huge volume.", why: "Massive produce throughput with grading and defect needs.", win: "Target a grading line; the throughput story scales fast." },
  { name: "Sun-Maid Growers", type: "Enterprise", vertical: "Food, Beverage & Packaging", region: "Central Valley & Coast", city: "Kingsburg", fit: "High", use: "Dried-fruit processing.", why: "Sorting plus packaging volume.", win: "Target sort/pack defect detection." },
  { name: "Beyond Meat", type: "Startup/Scale-up", vertical: "Food, Beverage & Packaging", region: "Greater LA / South Bay", city: "El Segundo", fit: "High", use: "Plant-based products.", why: "Packaged-food production with defect and packaging QC.", win: "Target packaging/portion inspection on a key line." },
  { name: "Dole Food", type: "Enterprise", vertical: "Food, Beverage & Packaging", region: "Greater LA / South Bay", city: "Westlake Village", fit: "High", use: "Packaged produce.", why: "Produce packaging and grading.", win: "Target a packaging line; expand by product." },

  // ---- Industrial & Advanced Manufacturing ----
  { name: "Parker Aerospace", type: "Enterprise", vertical: "Industrial & Advanced Mfg", region: "Orange County", city: "Irvine", fit: "Very High", use: "Flight-critical fluid and motion parts.", why: "Safety-critical components with traceability needs.", win: "Lead with escape cost; eval on a high-rework machined part." },
  { name: "Honeywell Aerospace", type: "Enterprise", vertical: "Industrial & Advanced Mfg", region: "Greater LA / South Bay", city: "Torrance", fit: "High", use: "Aerospace components.", why: "Mechanical assemblies with mixed automation.", win: "Target a manual inspection station carrying high rework cost." },
  { name: "Solar Turbines (Caterpillar)", type: "Enterprise", vertical: "Industrial & Advanced Mfg", region: "San Diego", city: "San Diego", fit: "Very High", use: "Industrial gas turbines.", why: "High-value rotating parts where defects are costly.", win: "Target blade/component inspection; quantify scrap + rework." },
  { name: "Keysight Technologies", type: "Enterprise", vertical: "Industrial & Advanced Mfg", region: "Bay Area", city: "Santa Rosa", fit: "High", use: "Electronic test and measurement.", why: "Precision electronics assembly.", win: "Target PCBA/instrument assembly defects." },
  { name: "Velo3D", type: "Startup/Scale-up", vertical: "Industrial & Advanced Mfg", region: "Bay Area", city: "Campbell", fit: "High", use: "Metal 3D-printing systems and parts.", why: "Additive parts with surface variation.", win: "Be the inspection layer for metal additive defects." },
  { name: "Upwing Energy", type: "Startup/Scale-up", vertical: "Industrial & Advanced Mfg", region: "Greater LA / South Bay", city: "Cerritos", fit: "High", use: "Gas-compression turbomachinery.", why: "Precision rotating machinery, low volume.", win: "Target rotor/precision-part inspection — and it's minutes from a Norwalk base." },
  { name: "Gateway Cities industrial base", type: "Cluster", vertical: "Industrial & Advanced Mfg", region: "Greater LA / South Bay", city: "Vernon", fit: "Very High", use: "Plastics, injection molding, metal fab cluster.", why: "Dense mid-market with manual inspection and tight margins.", win: "Land one first-station win, then reference-sell across the cluster's many shops." }
];
